### PR TITLE
V4 Rewrite

### PR DESCRIPTION
**Pull request by matt-major**
After neglecting the project for some time, here is the ongoing rewrite to reach v4.0.0.

This will move the source to TypeScript, add type definitions, improve extensibility etc.

As part of this rewrite **support for callbacks will be dropped** with preference being given to the use of Promises instead.

Methods still being migrated over and types being added. Plan is for this to be completed by the end of 2019.

### CODE REVIEW

**Comment by millette** [comment]
Do you have any plans to replace the `request` dependency?

**Comment by matt-major** [comment]
@millette I hadn't considered it until now, any particular reason for not using `request`? :)

**Comment by millette** [comment]
@matt-major Basically, it was the March announcement:

> The most valuable thing request can do for the JavaScript ecosystem is to go into maintenance mode and stop considering new features or major releases. -- <https://github.com/request/request/issues/3142>

Related issue: <https://github.com/request/request/issues/3143>

**Comment by sindresorhus** [comment]
If you're willing to give [Got](https://github.com/sindresorhus/got) a try, we have a [migration guide](https://github.com/sindresorhus/got/blob/master/documentation/migration-guides.md#migrating-from-request) for moving to Got from Request.

**Pull request closed without merging**
