### PR TITLE
Add Databases

### PR DESCRIPTION
**Pull request by satyarohith**

### CODE REVIEW

**Comment by satyarohith** [comment]
@matt-major Everything is done! Let me know if anything needs my attention. :tada:

**Comment by satyarohith** [comment]
@matt-major :)

**Comment by matt-major** [comment]
@satyarohith apologies for the delay, merging this now.

**Comment by bjorntheart** [comment]
@satyarohith Great work!

**Comment by satyarohith** [comment]
@bjorntheart Thank you, Björn!

**Pull request merged**
